### ISSUE TITLE
Create Score command

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli-cli#26]
Spawned from #23.  We would like to use Freshli in continuous integration (CI) builds to calculate the Freshness score of the project for the commit being built.  To do this we will need a Freshli-CLI to return a Freshness score for the current commit which the Freshli-CLI does not support.

The command should look something like:

```bash
freshli-cli score [threshold] [--directory directory]
```

The score command will analysis dependencies in the current directly, or in the directory argument, and return a Freshness score.  The Freshness score will be a single number that represents the Freshness for the entire directory.  For example if the directory has NuGet and NPM packages it will return the score both files combined.

If the Freshness score is greater then then threshold argument the command will fail.  For example, if the a project always wants a Freshness score of 10 or less then they would run a command like:

```bash
freshli-cli score 10
```

In a GitHub Action I see using it as:

```yml
# Assume .NET 5.0 is installed.
- name: Run Freshli
  run: |
    dotnet tools install freshli-cli
    freshli-cli score 10
```

If you want the Freshness value to use in a different GitHub action:

```yml
- name: Run Freshli
  id: freshli
  run: |
      dotnet tools install freshli-cli
      echo "::set-output name=FRESHNESS::$(freshli-cli score)"

- name: Display Freshness
  run: echo "Freshness: ${{ steps.freshli.outputs.FRESHNESS }}"
```

I don't think Freshli-Lib currently supports computing just the Freshness score for the currently checked out commit.  If not we will have to add the API methods.
