### ISSUE TITLE
Warning when adding assets to GitHub release in CI

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli-cli#33]
When running the CI the following warning is displayed:

```
##[warning]Unexpected input(s) 'tagName', valid inputs are ['owner', 'repository', 'token', 'milestone', 'assets', 'targetDirectory']
```

This is linked to the following CI step in [ci.yml](https://github.com/corgibytes/freshli-cli/blob/main/.github/workflows/ci.yml):

```
- name: "[Post Build] - Add Assets to Release Draft"
  if: ${{ github.event_name == 'push' }}
  uses: gittools/actions/gitreleasemanager/addasset@v0.9.9
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    owner: 'corgibytes'
    repository: 'freshli-cli'
    milestone: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
    tagName: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
    assets: 'freshli-cli-${{ steps.gitversion.outputs.majorMinorPatch }}-win-x64.zip,freshli-cli-${{ steps.gitversion.outputs.majorMinorPatch }}-linux-x64.zip,freshli-cli-${{ steps.gitversion.outputs.majorMinorPatch }}-osx-x64.zip'
```

I don't think the tagName is valid argument, at least not anymore.

https://github.com/GitTools/actions/blob/main/gitreleasemanager/addasset/action.yml
